import Head from 'next/head'
import { Inter } from 'next/font/google'
import CTA from '@/components/cta'
import Testimonials from '@/components/testimonials'
import FAQ from '@/components/faq'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Changemakers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CTA />
        <Testimonials />
        <FAQ />
      </main>
    </>
  )
}